from pathlib import Path
from uuid import uuid4

from sqlmodel import select

from app.models.log_file import LogFile
from app.models.user import User


AUTH_PREFIX = "/api/v1/auth"
UPLOAD_ENDPOINT = "/api/v1/uploads"


def create_test_user(client):
    suffix = uuid4().hex[:10]

    user = {
        "username": f"logsecurity_{suffix}",
        "email": f"logsecurity_{suffix}@example.com",
        "password": "Password123!",
        "full_name": "Log File Security Test User",
    }

    response = client.post(
        f"{AUTH_PREFIX}/register",
        json=user,
    )

    assert response.status_code == 201

    return user


def login_user(client, user):
    response = client.post(
        f"{AUTH_PREFIX}/login",
        data={
            "username": user["email"],
            "password": user["password"],
        },
    )

    assert response.status_code == 200

    return response.json()


def auth_headers(access_token):
    return {
        "Authorization": f"Bearer {access_token}",
    }


def get_db_user(db_session, credentials):
    return db_session.exec(
        select(User).where(
            User.email == credentials["email"]
        )
    ).first()
    
    
def test_uploaded_log_file_is_owned_by_authenticated_user(
    client,
    db_session,
):
    user = create_test_user(client)
    tokens = login_user(client, user)

    payload = (
        b"ownership-test-"
        + uuid4().hex.encode()
    )

    response = client.post(
        UPLOAD_ENDPOINT,
        headers=auth_headers(tokens["access_token"]),
        files={
            "file": (
                "owned-log.log",
                payload,
                "text/plain",
            )
        },
    )

    assert response.status_code == 200

    db_user = get_db_user(
        db_session,
        user,
    )

    assert db_user is not None

    file_hash = __import__(
        "app.utils.hash_utils",
        fromlist=["generate_sha256"],
    ).generate_sha256(payload)

    log_file = db_session.exec(
        select(LogFile).where(
            LogFile.sha256_hash == file_hash
        )
    ).first()

    assert log_file is not None
    assert log_file.user_id == db_user.id
    
    
def test_log_file_cannot_be_owned_by_another_user(
    client,
    db_session,
):
    user_a = create_test_user(client)
    user_b = create_test_user(client)

    tokens_b = login_user(client, user_b)

    payload = (
        b"user-b-private-log-"
        + uuid4().hex.encode()
    )

    response = client.post(
        UPLOAD_ENDPOINT,
        headers=auth_headers(tokens_b["access_token"]),
        files={
            "file": (
                "user-b-private.log",
                payload,
                "text/plain",
            )
        },
    )

    assert response.status_code == 200

    user_a_db = get_db_user(
        db_session,
        user_a,
    )

    user_b_db = get_db_user(
        db_session,
        user_b,
    )

    assert user_a_db is not None
    assert user_b_db is not None

    file_hash = __import__(
        "app.utils.hash_utils",
        fromlist=["generate_sha256"],
    ).generate_sha256(payload)

    log_file = db_session.exec(
        select(LogFile).where(
            LogFile.sha256_hash == file_hash
        )
    ).first()

    assert log_file is not None

    assert log_file.user_id == user_b_db.id
    assert log_file.user_id != user_a_db.id
    
def test_unauthenticated_user_cannot_upload_log_file(client):
    response = client.post(
        UPLOAD_ENDPOINT,
        files={
            "file": (
                "unauthorized.log",
                b"unauthorized upload",
                "text/plain",
            )
        },
    )

    assert response.status_code == 401
    
def test_log_file_storage_path_is_not_client_controlled(
    client,
    db_session,
):
    user = create_test_user(client)
    tokens = login_user(client, user)

    payload = (
        b"storage-isolation-"
        + uuid4().hex.encode()
    )

    response = client.post(
        UPLOAD_ENDPOINT,
        headers=auth_headers(tokens["access_token"]),
        files={
            "file": (
                "../../private/secret.log",
                payload,
                "text/plain",
            )
        },
    )

    assert response.status_code == 200

    data = response.json()

    stored_filename = data["saved_as"]
    storage_path = Path(data["file_path"])

    assert "/" not in stored_filename
    assert "\\" not in stored_filename
    assert ".." not in stored_filename

    # The returned path must not contain the client filename.
    assert "private" not in str(storage_path).lower()
    assert "secret.log" not in str(storage_path).lower()

    # Storage filename is generated by the server.
    assert stored_filename != "../../private/secret.log"