"""create parsed_logs table

Revision ID: 3944196aac47
Revises: 72f5680062b8
Create Date: 2026-08-04 19:45:24.112701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '3944196aac47'
down_revision: Union[str, Sequence[str], None] = '72f5680062b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parsed_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('log_file_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('component', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('raw_line', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('log_metadata', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['log_file_id'], ['log_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parsed_logs_log_file_id'), 'parsed_logs', ['log_file_id'], unique=False)
    op.create_index(op.f('ix_parsed_logs_severity'), 'parsed_logs', ['severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parsed_logs_severity'), table_name='parsed_logs')
    op.drop_index(op.f('ix_parsed_logs_log_file_id'), table_name='parsed_logs')
    op.drop_table('parsed_logs')
    # ### end Alembic commands ###
