"""add sha256 hash to log_files

Revision ID: 72f5680062b8
Revises: b8fd486f5883
Create Date: 2026-08-04 13:56:13.982886

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '72f5680062b8'
down_revision: Union[str, Sequence[str], None] = 'b8fd486f5883'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    "log_files",
    sa.Column(
        "sha256_hash",
        sqlmodel.sql.sqltypes.AutoString(),
        nullable=True,
    ),
)
    op.create_index(op.f('ix_log_files_sha256_hash'), 'log_files', ['sha256_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_log_files_sha256_hash'), table_name='log_files')
    op.drop_column('log_files', 'sha256_hash')
    # ### end Alembic commands ###
