"""create investigation_history table

Revision ID: 946fa8039b15
Revises: 9d9b81acbe89
Create Date: 2026-08-03 21:56:10.832707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '946fa8039b15'
down_revision: Union[str, Sequence[str], None] = '9d9b81acbe89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investigation_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investigation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('CREATED', 'UPDATED', 'STATUS_CHANGED', 'DELETED', name='investigationaction'), nullable=False),
    sa.Column('old_value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('new_value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigation_history_investigation_id'), 'investigation_history', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_investigation_history_user_id'), 'investigation_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_investigation_history_user_id'), table_name='investigation_history')
    op.drop_index(op.f('ix_investigation_history_investigation_id'), table_name='investigation_history')
    op.drop_table('investigation_history')
    # ### end Alembic commands ###
