"""add notification read state

Revision ID: cd1f07015f86
Revises: fcaab11826e4
Create Date: 2026-08-08 16:16:57.546599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'cd1f07015f86'
down_revision: Union[str, Sequence[str], None] = 'fcaab11826e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        "notifications",
        sa.Column(
            "is_read",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )

    op.add_column(
        "notifications",
        sa.Column(
            "read_at",
            sa.DateTime(),
            nullable=True,
        ),
    )

    op.create_index(
        op.f("ix_notifications_is_read"),
        "notifications",
        ["is_read"],
        unique=False,
    )

    # Existing and newly created rows are initialized as unread.
    # Remove the database-level default after migration.
    op.alter_column(
        "notifications",
        "is_read",
        server_default=None,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_column('notifications', 'read_at')
    op.drop_column('notifications', 'is_read')
    # ### end Alembic commands ###
