"""add report history

Revision ID: d6b1ee93938f
Revises: 7209193b8be9
Create Date: 2026-09-17 12:31:22.387489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6b1ee93938f'
down_revision: Union[str, Sequence[str], None] = '7209193b8be9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('investigation_id', sa.Integer(), nullable=True),
    sa.Column('report_type', sa.String(), nullable=False),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_history_created_at'), 'report_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_report_history_format'), 'report_history', ['format'], unique=False)
    op.create_index(op.f('ix_report_history_investigation_id'), 'report_history', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_report_history_report_type'), 'report_history', ['report_type'], unique=False)
    op.create_index(op.f('ix_report_history_status'), 'report_history', ['status'], unique=False)
    op.create_index(op.f('ix_report_history_user_id'), 'report_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_history_user_id'), table_name='report_history')
    op.drop_index(op.f('ix_report_history_status'), table_name='report_history')
    op.drop_index(op.f('ix_report_history_report_type'), table_name='report_history')
    op.drop_index(op.f('ix_report_history_investigation_id'), table_name='report_history')
    op.drop_index(op.f('ix_report_history_format'), table_name='report_history')
    op.drop_index(op.f('ix_report_history_created_at'), table_name='report_history')
    op.drop_table('report_history')
    # ### end Alembic commands ###
