from pydantic import BaseModel, Field


class HypothesisResponse(BaseModel):
    """
    A single hypothesis generated by the reasoning model.
    """

    cause: str = Field(
        ...,
        description="Possible root cause",
    )

    confidence: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Confidence from 0 to 1",
    )

    supporting_evidence: list[str] = Field(
        default_factory=list,
    )

    contradicting_evidence: list[str] = Field(
        default_factory=list,
    )


class HypothesisAnalysisResponse(BaseModel):
    """
    Structured response from the LLM reasoning step.
    """

    hypotheses: list[HypothesisResponse] = Field(
        default_factory=list,
    )
